#!/bin/bash

# reach avoid
python3 scripts/rsm_loop.py --exp_name lds_old --load_from_brax --initialize sac --plot --learner_batch_size 32k --batch_size 32k --env v2lds --model mlp --norm l1 --ds_type all --v_lr 0.0005 --p_lr 0.000005 --lip_lambda 0.001 --train_p 3 --eps 0.3 --p_lip 4 --v_lip 15 --prob 0.95 --min_iters 0 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --spec reach_avoid --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/lds_old_reach_avoid_loop_5.jax
python3 scripts/rsm_loop.py --exp_name lds_new --load_from_brax --initialize sac --plot --learner_batch_size 32k --batch_size 32k --env v2lds --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.995 --prob 0.995 --min_iters 0 --train_p 3 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 10 --improved_loss --policy_rollback --estimate_expected_via_ibp --spec reach_avoid --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/lds_new_reach_avoid_loop_15.jax

python3 scripts/rsm_loop.py --exp_name pend_old --initialize ppo --plot --learner_batch_size 16k --batch_size 32k --env v2pend_200 --model mlp --norm linf --ds_type all --v_lr 0.0005 --p_lr 0.00005 --lip_lambda 0.001 --train_p 3 --eps 0.01 --p_lip 4 --v_lip 15 --prob 0.9 --min_iters 0 --hidden_p 128 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --env_dim 4 --ppo_iters 200 --spec reach_avoid --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/pend_old_reach_avoid_loop_14.jax
python3 scripts/rsm_loop.py --exp_name pend_new --initialize ppo --plot --learner_batch_size 32k --batch_size 32k --env v2pend_100 --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.99 --prob 0.99 --min_iters 3 --train_p 3 --hidden_p 128 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 10 --improved_loss --policy_rollback --estimate_expected_via_ibp --spec reach_avoid --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/pend_new_reach_avoid_loop_7.jax

python3 scripts/rsm_loop.py --exp_name cavoid_old --initialize ppo --plot --learner_batch_size 16k --batch_size 32k --env v2cavoid_100 --model mlp --norm linf --ds_type all --v_lr 0.0005 --p_lr 0.00005 --lip_lambda 0.001 --train_p 3 --eps 0.05 --p_lip 4 --v_lip 15 --prob 0.9 --min_iters 0 --hidden_p 128 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --env_dim 4 --ppo_iters 100 --spec reach_avoid --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/cavoid_old_reach_avoid_loop_12.jax
python3 scripts/rsm_loop.py --exp_name cavoid_new --load_from_brax --initialize sac --plot --learner_batch_size 32k --batch_size 32k --env v2cavoid --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.97 --prob 0.97 --min_iters 0 --train_p 0 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 10 --improved_loss --policy_rollback --estimate_expected_via_ibp --spec reach_avoid --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/cavoid_new_reach_avoid_loop_4.jax

python3 scripts/rsm_loop.py --exp_name tri_new --load_from_brax --initialize sac --plot --learner_batch_size 8k --batch_size 32k --env vtri --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.95 --prob 0.95 --min_iters 0 --train_p 0 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 4 --improved_loss --policy_rollback --estimate_expected_via_ibp --spec reach_avoid --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/tri_new_reach_avoid_loop_9.jax

python3 scripts/rsm_loop.py --exp_name human2_new --load_from_brax --initialize sac --plot --learner_batch_size 32k --batch_size 32k --env vhuman2 --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.8 --prob 0.8 --min_iters 0 --train_p 0 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 3 --improved_loss --policy_rollback --estimate_expected_via_ibp --spec reach_avoid --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/human2_new_reach_avoid_loop_31.jax

# stability
python3 scripts/rsm_loop.py --exp_name slds_new --load_from_brax --initialize sac --plot --learner_batch_size 32k --batch_size 32k --env v2lds --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.99 --prob 1 --min_iters 0 --train_p 3 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 10 --improved_loss --policy_rollback --estimate_expected_via_ibp --spec stability --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/lds_new_stability_loop_1.jax

python3 scripts/rsm_loop.py --exp_name spend_old --initialize ppo --plot --learner_batch_size 16k --batch_size 32k --env vpend_200 --model mlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.001 --train_p 3 --eps 0.01 --p_lip 4 --v_lip 15 --prob 1 --min_iters 0 --hidden_p 128 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --spec stability --ppo_iters 200 --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/pend_old_stability_loop_8.jax
python3 scripts/rsm_loop.py --exp_name spend_new --load_from_brax --initialize sac --plot --learner_batch_size 32k --batch_size 32k --env vpend --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.9 --prob 1 --v_lip 0 --min_iters 0 --train_p 0 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 10 --improved_loss --policy_rollback --estimate_expected_via_ibp --spec stability --init_with_static --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/pend_new_stability_loop_4.jax

python3 scripts/rsm_loop.py --exp_name scavoid_new --load_from_brax --initialize sac --plot --learner_batch_size 32k --batch_size 32k --env v2cavoid --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.99 --prob 1 --min_iters 0 --train_p 3 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 3 --improved_loss --policy_rollback --estimate_expected_via_ibp --spec stability --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/cavoid_new_stability_loop_16.jax

python3 scripts/rsm_loop.py --exp_name stri_new --load_from_brax --initialize sac --plot --learner_batch_size 8k --batch_size 32k --env vtri --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.99 --prob 1 --min_iters 0 --train_p 0 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 4 --improved_loss --policy_rollback --estimate_expected_via_ibp --spec stability --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/tri_new_stability_loop_1.jax

python3 scripts/rsm_loop.py --exp_name slds4d_new --load_from_brax --initialize sac --plot --learner_batch_size 32k --batch_size 32k --env v2ldss4 --model tmlp --norm linf --ds_type all --v_lr 0.0001 --p_lr 0.000001 --lip_lambda 0.2 --rollback_threshold 0.99 --prob 1 --min_iters 0 --train_p 0 --hidden_p 256 --hidden_v 256 --grid_size 32M --buffer_size 6000000 --n_local 3 --improved_loss --policy_rollback --estimate_expected_via_ibp --env_dim 4 --spec stability --continue_rsm 1 --skip_initialize --no_train --rsm_path scripts/checkpoints/ldss4_new_stability_loop_14.jax 