# NeuralStoc Configuration File

# Experiment Settings
plot: true  # Whether to plot results
logger_level: "INFO"  # Logger level: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"

# Training Parameters
p_lr: 0.00005  # Learning rate for policy network
c_lr: 0.0005  # Learning rate for critic
v_lr: 0.0005  # Learning rate for V network
lip_lambda: 0.2  # Lipschitz estiamtion coefficient
model: "tmlp"  # Model type: "mlp" or "tmlp"
initial_epochs: 200  # Number of training epochs before first verification
epochs: 50  # Number of training epochs after each verification

# Verification Parameters
n_local: 1  # Number of ticks per dimension in the local Lipschitz constant estimation grid

# Batch, Grid, and Bound Computation Sizes - Timeout (in minutes)
batch_size: "32k"  # Batch size for verification
learner_batch_size: "8k"  # Batch size for learning
# grid_size: "32M"  # Grid size for verification
grid_size: "1M"
# buffer_size: 6000000  # Buffer size
buffer_size: 150000
bound_co_factor: 1  # Co-factor for the bound computation grid size
timeout: 1440  # Timeout in minutes (default: 24 hours)

# PPO Settings
n_step: 1  # Number of steps per PPO update
std_start: 1.0  # Starting standard deviation for PPO
std_end: 0.05  # Ending standard deviation for PPO
normalize_r: 0  # Normalize rewards for PPO
normalize_a: 1  # Normalize actions for PPO

# Advanced Options
norm: "linf"  # Norm type: "l1" or "linf"
ds_type: "all"  # Dataset type
improved_loss: true  # Use improved loss function
policy_rollback: true  # Use policy rollback
estimate_expected_via_ibp: true  # Estimate expected value via IBP